### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by nazir-ali-332** [paulyehtw/Lidar-and-Radar-sensor-fusion-with-Extended-Kalman-Filter#1]
Hello, 

hope you are doing good.
I have been going  through your code and there are few questions i would like to ask and would be thankful if you could answer them.

You created few matrices like B, F, P, R_l, R_r, Q, H, what does these matrices indicate ? and how are you using them ?

Would be very helpful if you could clear this please.

Thank You

Regards,
Nazir Ali

**Comment by paulyehtw** [comment]
please check the formula in any paper regarding EKF.
